### ISSUE TITLE
Kurt wants to be able to play the keyboard

### ISSUE THREAD

**Issue by zaporter-work** [michealparks/me#6]

**Comment by ethanlookpotts** [comment]
I am also facing this issue. Any updates on when this will be fixed?

**Comment by zaporter-work** [comment]
[Progress will not happen until there is new maintainer. parks.lol has sparse 
commit log too. Ethan you are better off waiting until new maintainer happens 
or fork yourself. Submitting patches here has no purpose these days. The 
current maintainer lost interest or doesn't care to maintain anymore. It is sad 
to see for a repo like this.](https://www.mail-archive.com/xz-devel@tukaani.org/msg00566.html)

**Comment by zaporter-work** [comment]
Closing because this pops up on my list of issues I am involved in (and it was a joke)

**Comment by michealparks** [comment]
Not done yet.

**Comment by michealparks** [comment]
Lol sorry, missed your comment, will close out of sympathy 😂
